---
- name: Apply sysctl configuration
  ansible.builtin.command: sysctl --system

- name: Reload udev rules
  ansible.builtin.command:
    argv:
      - /bin/sh
      - -c
      - udevadm control --reload-rules && udevadm trigger
