---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  when: not ansible_check_mode

- name: Restart blocky
  ansible.builtin.systemd:
    name: blocky
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"
  when: not ansible_check_mode

- name: Restart unbound
  ansible.builtin.systemd:
    name: unbound
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"
  when: not ansible_check_mode
